on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - id: greet
      uses: moddyz/HelloWorldCompositeRunStepsAction@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.greet.outputs.random-number }}
      shell: bash
